spring.application.name=messenger

# JWT
jwt.secret=d05d899f3c4cc402378fe47237ec16d9cd11b1ab68be28eebc1ee07f7bdc7e15
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=2592000000

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:h2:mem:messengerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379